// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function BatchUpsertRules(arg1:model.BatchRuleRequest):Promise<model.BatchRuleResult>;

export function ClearLogs():Promise<model.AppState>;

export function DeleteRule(arg1:string):Promise<model.AppState>;

export function DisableSystemPac():Promise<void>;

export function EnableSystemPac():Promise<void>;

export function ExportAgentDiagnostics():Promise<string>;

export function ExportConfig():Promise<void>;

export function GetAgentDiagnostics():Promise<model.AgentDiagnostics>;

export function GetState():Promise<model.AppState>;

export function ImportConfig():Promise<model.AppState>;

export function MoveRule(arg1:string,arg2:string):Promise<model.AppState>;

export function OpenConfigLocation():Promise<void>;

export function OpenDataDirectory():Promise<void>;

export function PauseTrafficRouting():Promise<model.AppState>;

export function RefreshStatus():Promise<model.AppState>;

export function SaveSettings(arg1:model.AppConfig):Promise<model.AppState>;

export function SetNetworkAdapterEnabled(arg1:string,arg2:boolean):Promise<model.AppState>;

export function StartPacService():Promise<void>;

export function StartProxyService():Promise<void>;

export function StartTunService():Promise<void>;

export function StopPacService():Promise<void>;

export function StopProxyService():Promise<void>;

export function StopTunService():Promise<void>;

export function UpsertRule(arg1:model.Rule):Promise<model.AppState>;
