// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchUpsertRules(arg1) {
  return window['go']['main']['App']['BatchUpsertRules'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function DisableSystemPac() {
  return window['go']['main']['App']['DisableSystemPac']();
}

export function EnableSystemPac() {
  return window['go']['main']['App']['EnableSystemPac']();
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportConfig() {
  return window['go']['main']['App']['ImportConfig']();
}

export function MoveRule(arg1, arg2) {
  return window['go']['main']['App']['MoveRule'](arg1, arg2);
}

export function OpenConfigLocation() {
  return window['go']['main']['App']['OpenConfigLocation']();
}

export function RefreshStatus() {
  return window['go']['main']['App']['RefreshStatus']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartPacService() {
  return window['go']['main']['App']['StartPacService']();
}

export function StartProxyService() {
  return window['go']['main']['App']['StartProxyService']();
}

export function StopPacService() {
  return window['go']['main']['App']['StopPacService']();
}

export function StopProxyService() {
  return window['go']['main']['App']['StopProxyService']();
}

export function UpsertRule(arg1) {
  return window['go']['main']['App']['UpsertRule'](arg1);
}
